export const COUNTRIES: Record<string, { name: string; flag: string }> = {
  AR: { name: "Argentina", flag: "🇦🇷" },
  AU: { name: "Australia", flag: "🇦🇺" },
  BR: { name: "Brasil", flag: "🇧🇷" },
  DE: { name: "Germany", flag: "🇩🇪" },
  ES: { name: "Spain", flag: "🇪🇸" },
  FR: { name: "France", flag: "🇫🇷" },
  GB: { name: "United Kingdom", flag: "🇬🇧" },
  IT: { name: "Italy", flag: "🇮🇹" },
  JP: { name: "Japan", flag: "🇯🇵" },
  MX: { name: "Mexico", flag: "🇲🇽" },
  US: { name: "United States", flag: "🇺🇸" },
  PR: { name: "Puerto Rico", flag: "🇵🇷" },
  GT: { name: "Guatemala", flag: "🇬🇹" },
  CL: { name: "Chile", flag: "🇨🇱" },
  NG: { name: "Nigeria", flag: "🇳🇬" },
  CO: { name: "Colombia", flag: "🇨🇴" },
  CU: { name: "Cuba", flag: "🇨🇺" },
};
